config/routes.rb
Rails.application.routes.draw do
  resources :categoria
  root "dashboard#index"
  resources :equipos 
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorium.rb
class Categorium < ApplicationRecord
end

app/models/equipo.rb
class Equipo < ApplicationRecord
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :equipo
  MovementTypes = {add: 0, remove: 1}
  validates:quantity, presence:true, numericality:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: %i[ show edit update destroy ]

  # GET /categoria or /categoria.json
  def index
    @categoria = Categorium.all
  end

  # GET /categoria/1 or /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria or /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to categorium_url(@categorium), notice: "Categorium was successfully created." }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1 or /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to categorium_url(@categorium), notice: "Categorium was successfully updated." }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1 or /categoria/1.json
  def destroy
    @categorium.destroy

    respond_to do |format|
      format.html { redirect_to categoria_url, notice: "Categorium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categorium_params
      params.require(:categorium).permit(:nombre, :descripcion)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/equipos_controller.rb
class EquiposController < ApplicationController
  before_action :set_equipo, only: %i[ show edit update destroy ]

  # GET /equipos or /equipos.json
  def index
    @equipos = Equipo.all
  end

  # GET /equipos/1 or /equipos/1.json
  def show
  end

  # GET /equipos/new
  def new
    @equipo = Equipo.new
  end

  # GET /equipos/1/edit
  def edit
  end

  # POST /equipos or /equipos.json
  def create
    @equipo = Equipo.new(equipo_params)

    respond_to do |format|
      if @equipo.save
        format.html { redirect_to equipo_url(@equipo), notice: "Equipo was successfully created." }
        format.json { render :show, status: :created, location: @equipo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipos/1 or /equipos/1.json
  def update
    respond_to do |format|
      if @equipo.update(equipo_params)
        format.html { redirect_to equipo_url(@equipo), notice: "Equipo was successfully updated." }
        format.json { render :show, status: :ok, location: @equipo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipos/1 or /equipos/1.json
  def destroy
    @equipo.destroy

    respond_to do |format|
      format.html { redirect_to equipos_url, notice: "Equipo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipo
      @equipo = Equipo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equipo_params
      params.require(:equipo).permit(:name, :description, :serial, :adquisition, :state, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/views/categoria/_categorium.html.erb
<div id="<%= dom_id categorium %>">
  <p>
    <strong>Nombre:</strong>
    <%= categorium.nombre %>
  </p>

  <p>
    <strong>Descripción:</strong>
    <%= categorium.descripcion %>
  </p>

</div>

app/views/categoria/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: @categorium do |f| %>
        <% if @categorium.errors.any? %>
          <div class="alert alert-danger">
            <ul>
              <% @categorium.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :nombre, "Nombre" %>
          <%= f.text_field :nombre, class: "form-control", placeholder: 'Nombre de la categoría' %>
        </div>
        <div class="form-group">
          <%= f.label :descripcion, "Descripción" %>
          <%= f.text_area :descripcion, class: "form-control", placeholder: 'Añada una descripción de la categoria' %>
        </div>
        <div class="form-group">
          <%= f.submit "Guardar categoría", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categoria/edit.html.erb
<h1>Editar categoría existente</h1><br>
<a class="btn btn-primary" href="<%= categoria_path(@categoria) %>">Regresar al listado</a>
<%= render 'form' %>
<br>
<div>
  <%= link_to "Ver detalles", @categoria, class:"btn btn-primary" %> |
  <%= link_to "Editar categoria", edit_categorium_path(@categorium), class:"btn btn-warning" %> |
</div>
<br>
  <%= button_to "Eliminar categoria", @categoria, method: :delete %>
  

app/views/categoria/index.html.erb
<h1>Listado de categorias</h1>
<a href="<%= new_categorium_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
  </span>
  <span class="text">Crear categoria</span>
</a>

<br><br>
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>

  </thead>
  <tbody>
    <% @categoria.each do |categoria| %>
    <tr>
      <td><%= categoria.nombre %></td>
      <td><%= categoria.descripcion %></td>

      <td><%= link_to "Detalles", categorium_path(categoria), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/categoria/new.html.erb
<h1>Crear nueva categoría</h1>
<br>
<a class="btn btn-primary" href="<%= categoria_path %>"> Regresar al listado de categorías</a><br>
<br>
<%= render "form", categoria: @categoria %>

app/views/categoria/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles de las categorías</h1>
    
    <%= link_to "Regresar al listado de categorías", categoria_path, class: 'btn btn-primary' %>
    <%= link_to "Editar", edit_categorium_path(@categorium), class: 'btn btn-warning' %>
    <br><br>
    <div class="card">
      <table class="table">
        <tr>
          <td><b>Nombre del equipo:</b></td>
          <td><%= @categorium.nombre %></td>
        </tr>
        <tr>
          <td><b>Descripcion:</b></td>
          <td><%= @categorium.descripcion %></td>
        </tr>
      </table>
    </div>
    <br>
    <%= button_to "Eliminar categoría", @categoria, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>

app/views/dashboard/index.html.erb
<h1>Plataforma de inventarios para equipos médicos utilizando Ruby Sinatra, PostgreSQL y Docker</h1>
<br>
<h2>Esta prueba tiene como objetivo mostrar mis habilidades y conocimientos en el desarrollo de aplicaciones web utilizando Ruby Sinatra, PostgreSQL y Docker,
centrándose en el contexto de una plataforma de inventarios para equipos médicos.</h2>

app/views/equipos/_equipo.html.erb
<div id="<%= dom_id equipo %>">
  <p>
    <strong>Name:</strong>
    <%= equipo.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= equipo.description %>
  </p>

  <p>
    <strong>Serial:</strong>
    <%= equipo.serial %>
  </p>

  <p>
    <strong>Adquisition:</strong>
    <%= equipo.adquisition %>
  </p>

  <p>
    <strong>State:</strong>
    <%= equipo.state %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= equipo.location %>
  </p>

</div>

app/views/equipos/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: @equipo do |f| %>
        <% if @equipo.errors.any? %>
          <div class="alert alert-danger">
            <ul>
              <% @equipo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, "Nombre" %>
          <%= f.text_field :name, class: "form-control", placeholder: 'Nombre del equipo' %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Descripción" %>
          <%= f.text_field :description, class: "form-control", placeholder: 'Descripción' %>
        </div>
        <div class="form-group">
          <%= f.label :serial, "Serial" %>
          <%= f.text_field :serial, class: "form-control", placeholder: 'Ingrese el serial del equipo' %>
        </div>
        <div class="form-group">
          <%= f.label :adquisition, "Adquisición" %>
          <%= f.text_field :adquisition, class: "form-control", placeholder: 'Ingrese el metodo de adquisición' %>
        </div>
        <div class="form-group">
          <%= f.label :state, "Estado" %>
          <%= f.text_field :state, class: "form-control", placeholder: 'Ingrese el estado del equipo' %>
        </div>
        <div class="form-group">
          <%= f.label :location, "Locación" %>
          <%= f.text_field :location, class: "form-control", placeholder: 'Ingrese la localización del equipo' %>
        </div>
        <div class="form-group">
          <%= f.submit "Guardar equipo", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/equipos/edit.html.erb
<h1>Editar equipo existente</h1><br>
<a class="btn btn-primary" href="<%= equipo_path(@equipo) %>">Regresar al listado</a>
<%= render 'form' %>

<br>
<div>
  <%= link_to "Ver detalles", @equipo, class:"btn btn-primary" %> |
  <%= link_to "Editar equipo", edit_equipo_path(@equipo), class:"btn btn-warning" %> |


  </div>
<br>
  <%= button_to "Eliminar equipo", @equipo, method: :delete %>
  

app/views/equipos/index.html.erb
<h1>Listado de equipos médicos</h1>
<a href="<%= new_equipo_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
    <i class="fas fa-flag"></i>
  </span>
  <span class="text">Registrar equipo</span>
</a>
<br><br>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Serial</th>
      <th>Adquisición</th>
      <th>Estado</th>
      <th>Locación</th>
  </thead>
  <tbody>
    <% @equipos.each do |equipo| %>
    <tr>
      <td><%= equipo.name %></td>
      <td><%= equipo.description %></td>
      <td><%= equipo.serial %></td>
      <td><%= equipo.adquisition %></td>
      <td><%= equipo.state %></td>
      <td><%= equipo.location %></td>
      <td><%= link_to "Detalles", equipo_path(equipo), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/equipos/new.html.erb
<h1>Crear nuevo equipo</h1>
<a class="btn btn-primary" href="<%= equipos_path %>"> Regresar al listado de productos</a><br>
<br>
<%= render "form", equipo: @equipo %>

app/views/equipos/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles del equipo</h1>
    <br>
    <%= link_to "Regresar al listado de equipos", equipos_path, class: 'btn btn-primary' %>
    <%= link_to "Editar", edit_equipo_path(@equipo), class: 'btn btn-primary' %><br><br>
    
    <div class="card">
      <table class="table">
        <tr>
          <td><b>Nombre del equipo:</b></td>
          <td><%= @equipo.name %></td>
        </tr>
        <tr>
          <td><b>Descripcion:</b></td>
          <td><%= @equipo.description %></td>
        </tr>
        <tr>
          <td><b>Serial:</b></td>
          <td><%= @equipo.serial %></td>
        </tr>
        <tr>
          <td><b>Adquisicion:</b></td>
          <td><%= @equipo.adquisition %></td>
        </tr>
        <tr>
          <td><b>Estado:</b></td>
          <td><%= @equipo.state %></td>
        </tr>
        <tr>
          <td><b>localizacion:</b></td>
          <td><%= @equipo.location %></td>
        </tr>
      </table>
    </div>
    <br>
    <%= button_to "Eliminar equipo", @equipo, method: :delete, class: 'btn btn-danger' %>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventario - RubyOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


  </head>

  <body id="page-top">
  <div id="wrapper">
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon rotate-n-15"> 
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">MEDICAL INVENTORY</div>
      </a>
      
      <hr class="sidebar-divider ">
        <li class="nav-item">
          <a class="nav-link" href="<%= equipos_path %>">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Equipos</span>
          
          </a>
        </li>
        <br>
      <hr class="sidebar-divider">
        <li class="nav-item">
          <a class="nav-link" href="<%= categoria_path %>">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Categorías</span>
          </a>
        </li>
        <br>
        <hr class="sidebar-divider">
    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
      <!-- Main Content -->
      <div id="content">
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
        </nav>
        <!-- End of Topbar -->
        <!-- Begin Page Content -->
        <div class="container-fluid">
          <!-- Page Heading -->
          <%= yield %>
        </div>
        <!-- /.container-fluid -->
      </div>
      <!-- End of Main Content -->
      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Elaborado por Sebastian Freire - 2023 </span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
  </div>
  <!-- End of Page Wrapper -->
  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
</body>
      

</html>